project_id = "fzltwigszgqtqagjgaer"

[functions]
  [functions.admin-delete-user]
    verify_jwt = true
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.delete-account]
    verify_jwt = true
  [functions.process-email-queue]
    verify_jwt = true
  [functions.ai-bio-assistant]
    verify_jwt = false
  [functions.ai-help-chat]
    verify_jwt = false
  [functions.ai-smart-search]
    verify_jwt = false
